### ISSUE TITLE
Error while deploying Subscription for APIM API using Bicep

### ISSUE THREAD

**Issue by arindamhazramsft** [Azure-Samples/azure-openai-apim-load-balancing#2]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
Run Sample.ipynb through Visual studio code
### Any log messages given by the failure
>
"details":[{"code":"LinkedInvalidPropertyId","message":"Property id '/apis/openai' at path 'properties.scope' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'."}]}]}]}}
### Expected/desired behavior
>
It should add a subscription for API OpenAI.
### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 11
### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jamesmcroft** [comment]
@arindamhazramsft I located the issue with the deployment. The Bicep template was using older API versions which caused an error in the infrastructure deploying successfully. 

If you could try again and let me know if this is now working for you, that would be appreciated.
